# Generated by Django 4.2.7 on 2023-11-20 14:04

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_category_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "ordering": ["name"],
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipments",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="api.category",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="categories",
            field=models.ManyToManyField(
                related_name="categories", to="api.category", verbose_name="Categories"
            ),
        ),
    ]
